site_name: Lexie's Note
site_url: https://slowist-lee.github.io/notebook/
theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/book
  favicon: images/favicon.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to system preference
  font: false
    # code: JetBrains Mono
  # icon:
    # logo: assets/logo.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    # - navigation.sections
    - navigation.indexes
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
repo_url: https://github.com/lexie-423/notebook-by-zizi
repo_name: Lexie's Notebook
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lexie-423
    - icon: fontawesome/regular/envelope
      link: mushroomzizi@outlook.com

  feedback:
    title: æ­¤é¡µé¢æœ‰å¸®åŠ©å—ï¼Ÿ
    ratings:
      - icon: material/thumb-up-outline
        name: This page was helpful
        data: 1
        note: >-
          è°¢è°¢ä½ çš„åé¦ˆï¼
      - icon: material/thumb-down-outline
        name: This page could be improved
        data: 0
        note: >-
          Thanks for your feedback! 

plugins:
  - mermaid2: {}
  - search
  - callouts
  - encryptcontent:
      title_prefix: 'ğŸ”’'
      summary: 'è¯·è¾“å…¥å¯†ç æŸ¥çœ‹.'
      encryption_info_message: 'æ­¤å†…å®¹å·²åŠ å¯†, è¯·è¾“å…¥å¯†ç æŸ¥çœ‹.'
      decryption_failure_message: 'å¯†ç é”™è¯¯, å¦‚æœ‰éœ€è¦ï¼Œè¯·è”ç³»Lexie.'
      hljs: False
      encrypted_something:
        mkdocs-encrypted-toc: [nav, class]
  - statistics
  - changelog
  - git-revision-date-localized:
      enable_creation_date: true 
  - toc
markdown_extensions:
  - attr_list
  - md_in_html
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list



  # - mdx_truly_sane_lists
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight: # ä»£ç å—é«˜äº®
      auto_title: false # æ˜¾ç¤ºç¼–ç¨‹è¯­è¨€åç§°
extra_javascript:
  - js/katex.js
  - js/extra.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

copyright: Copyright &copy; 2025 Lexie/All Rights Reserved. # å·¦ä¸‹è§’çš„ç‰ˆæƒå£°æ˜

nav:
  - Home:
    - index.md
    - æ›´æ–°è®°å½•: changelog.md
    - å‹é“¾: Friends.md
    - ç¬”è®°ç›®å½•: Content.md
    - To Do List: Writings/essay/22.md
  - Computer Science:
    - cs/index.md
    - Language:
      - C:
        - cs/pl/C/index.md
        - Previous: cs/pl/C/PreviousNote.md
        - Ch7 Pointer: cs/pl/C/Pointer.md
        - Ch8 String: cs/pl/C/String.md
        - Ch9 Structure: cs/pl/C/Structure.md
        - Ch10 Linked List: cs/pl/C/LinkedList.md
        - Ch12 File: cs/pl/C/file.md
        - Error: cs/pl/C/Error-Sum.md
        - Misc: cs/pl/C/misc.md
      - Cpp:
        - cs/pl/cpp/index.md
        - Basic: cs/pl/cpp/Basic.md
      - Asm:
        - cs/pl/Asm/index.md
        - ç†è®ºå¤ä¹ : cs/pl/Asm/sum.md
        - Exercise: cs/pl/Asm/Exercise.md
        - Answer: cs/pl/Asm/Answer.md
        - Misc: cs/pl/Asm/Misc.md
    - Algorithm:
      - cs/algorithm/index.md
      - cs61b:
        - Note:
          - Lecture1 Introduction: cs/algorithm/cs61b/Lecture1_Introduction.md
          - Lecture2 Defining and Using Classes: cs/algorithm/cs61b/Lecture2_Defining and Using Classes.md
          - Lecture3 ListsI References Recursion and Lists: cs/algorithm/cs61b/Lecture3_ListsI_References_Recursion_and_Lists.md
          - Lecture4: cs/algorithm/cs61b/Lecture4.md
        - Labs:
          - signup: cs/algorithm/cs61b/Sign_up.md
          - HW0: cs/algorithm/cs61b/HW0.md
          - HW0B: cs/algorithm/cs61b/HW0B.md
          - lab1: cs/algorithm/cs61b/Lab1_Note.md
          - proj1: cs/algorithm/cs61b/Proj1_Summary.md
      - ç®—æ³•è®¾è®¡ä¸æ™ºèƒ½è®¡ç®—(ä¿¡ç”µ):
        - cs/algorithm/ds/index.md
      # - æ•°æ®ç»“æ„åŸºç¡€:
      #   - cs/algorithm/fds/index.md
    - System: 
      - cs/system/index.md
      - CO:
        - cs/system/CO/index.md
        - 1. Introduction: cs/system/CO/1.md
      - DD:
        - cs/system/DD/index.md
        - verilog: cs/system/dd/verilog.md
        - note: cs/system/dd/note.md
        - experiment: cs/system/dd/report.md
    - Tools:
      - cs/tools/index.md
      - 1. Git: cs/tools/git-advance.md
      - 2. PA0: cs/tools/PA0.md
      - 3. WSL: cs/tools/WSL.md
    - CTF:
      - cs/ctf/index.md
      - Lab0:
        - Part 1: cs/ctf/lab0/lab0-1.md
        - Part 2: cs/ctf/lab0/lab0-2.md
      - web:
        - Note 1: cs/ctf/web/note-1.md
        - Note 2: cs/ctf/web/note-2.md
        - Lab 1: cs/ctf/web/lab-1.md
        - Lab 2: cs/ctf/web/lab-3.md
      - misc:
        - Note: cs/ctf/misc/note-2.md
        - Lab: cs/ctf/misc/misc-lab1.md
      - pwn:
        - cs/ctf/pwn/index.md
      - reverse:
        - cs/ctf/reverse/index.md
      - crypto:
        - cs/ctf/crypto/index.md
    - è®¡ç®—æœºç§‘å­¦åŸºç¡€(A):
      - cs/fundamental/index.md
      - Note | ç¬”è®°: cs/fundamental/note.md
      - Office | æœŸä¸­: cs/fundamental/office.md
      - Test | è‡ªæµ‹: cs/fundamental/test.md
  - AI:
    - AI/index.md
    - æ·±åº¦å­¦ä¹ : 
      - AI/DL/index.md
      - 1. Pytorch åŸºç¡€ä½¿ç”¨: AI/DL/1.md
      - 2.è‡ªåŠ¨å¾®åˆ†çš„Pytorchå®ç°: AI/DL/2.md
    - æœºå™¨å­¦ä¹ :
      - AI/ML/index.md
      - 0. æœºå™¨å­¦ä¹ æ¦‚è¿°: AI/ML/0.md
      - 1. ç»Ÿè®¡å­¦ä¹ &ç›‘ç£å­¦ä¹ æ¦‚è®º: AI/ML/1.md
      - 2. æ„ŸçŸ¥æœº: AI/ML/2.md
      - 3. SVMç®—æ³•: AI/ML/3.md
    - å…¶ä»–çŸ¥è¯†:
      - AI/Others/index.md
      - 1. æœç´¢: AI/Others/Search.md
  - Math: 
    - Math/index.md
    - å¤å˜å‡½æ•°ä¸ç§¯åˆ†å˜æ¢: Math/complex/index.md
    - æ¦‚ç‡è®ºä¸æ•°ç†ç»Ÿè®¡: Math/Probability/Error.md
    - æ•°å­¦å»ºæ¨¡: 
      - Math/MathModel/index.md
      - 1. æ•°å­¦è§„åˆ’: Math/MathModel/program/program.md
      - 2. å›¾è®ºæ¨¡å‹: Math/MathModel/graph/graph.md
      - 3. ç»„åˆä¼˜åŒ–: Math/MathModel/combination-optimize/note.md
      - 4. ä¹ é¢˜ç¬”è®°: Math/MathModel/exercise/index.md
      - 5. Review: Math/MathModel/review/note.md
      - 6. Test:
        - 24-25ç§‹å†¬æœŸæœ«(ACEE): Math/MathModel/test/index.md
  - ISEE: 
    - isee/index.md
    - é€šä¿¡åŸç†:
      - Lec 4: isee/communication/4.md
    - ä¿¡æ¯ç†è®º:
      - isee/information/index.md
      - ç¬¬ä¸€èŠ‚ã€ä¿¡æ¯çš„åº¦é‡: isee/information/1.md
      - ç¬¬äºŒèŠ‚ã€éšæœºå˜é‡çš„ç†µ: isee/information/2.md
      - ç¬¬ä¸‰èŠ‚ã€éšæœºå˜é‡çš„å¹³å‡äº’ä¿¡æ¯: isee/information/3.md
      - ç¬¬å››èŠ‚ã€è¿ç»­éšæœºå˜é‡çš„äº’ä¿¡æ¯å’Œå¾®åˆ†ç†µ: isee/information/4.md
      - ç¬¬äº”è®²ã€å¹³ç¨³ç¦»æ•£ä¿¡æºçš„ç†µ: isee/information/5.md
      - ç¬¬å…­èŠ‚ã€ä¿¡æ¯çš„æ— æŸå‹ç¼©: isee/information/6.md
      - ç¬¬ä¸ƒèŠ‚ã€ç­‰é•¿ç¼–ç : isee/information/7.md
      - ç¬¬å…«èŠ‚ã€ä¸ç­‰é•¿ç¼–ç : isee/information/8.md
      - ç¬¬ä¹èŠ‚ã€ç¼–ç æ–¹å¼: isee/information/9.md
      - ç¬¬åèŠ‚ã€ç¦»æ•£æ— è®°å¿†ä¿¡é“: isee/information/10.md
      - ç¬¬åä¸€èŠ‚ã€ä¿¡é“çš„ç»„åˆ: isee/information/11.md
      - ç¬¬åäºŒèŠ‚ã€ç¦»æ•£æ— è®°å¿†ä¿¡é“å®¹é‡: isee/information/12.md
      - ç¬¬åä¸‰èŠ‚ã€åŠ æ€§é«˜æ–¯å™ªå£°ï¼ˆAWGNï¼‰ä¿¡é“: isee/information/13.md
      - ç¬¬åå››èŠ‚ã€ä¿¡æ¯çš„æœ‰æŸå‹ç¼©: isee/information/14.md
      - ç¬¬ä¸‰ç« å¤ä¹ æ€»ç»“: isee/information/Chap3Review.md
    - ç”µå­ç”µè·¯åŸºç¡€: 
      - isee/elec/index.md
      - å­¦ä¹ è·¯å¾„: isee/elec/share.md
      - ç”µè·¯éƒ¨åˆ†:
        - åŸºæœ¬æ¦‚å¿µ: 
          - isee/elec/EC/concepts/index.md
        - åŠ¨æ€ç”µè·¯æ—¶åŸŸåˆ†æ: 
          - isee/elec/EC/transition/index.md
        - ç›¸é‡åˆ†æ: 
          - isee/elec/EC/phasor/index.md
        - æœŸæœ«è¡¥å¤©: 
          - isee/elec/EC/all/index.md
      - æ¨¡ç”µéƒ¨åˆ†:
        - BJT:
          - isee/elec/bjt/index.md
        - MOS:
          - isee/elec/MOS/index.md
        - å¤šçº§ã€å·®åˆ†:
          - isee/elec/Hard/index.md
        - è¿ç®—æ”¾å¤§å™¨:
          - isee/elec/opam/index.md
        - é¢‘ç‡å“åº”:
          - isee/elec/freq/index.md
        - åé¦ˆ:
          - isee/elec/feedback/index.md
        - åŠŸç‡æ”¾å¤§å™¨:
          - isee/elec/pa/index.md
      - æœŸæœ«è¯•é¢˜:
        - isee/elec/test.md
    - ç”µå­ç”µè·¯è®¾è®¡å®éªŒI:
      - isee/elec-exp1/index.md
  - English:
    - English/index.md
    - Interpretation: 
      - English/Interpretation/index.md
      - å­¦ä¹ ä½“éªŒ:
        - English/Interpretation/experience/Harvest.md
        - English/Interpretation/experience\Interpretation--Self Assessment.md
      - HW && Topic: 
        - English/Interpretation/homework/Welcome Speech.md
        - English/Interpretation/homework/City and Travel.md
        - English/Interpretation/homework/Culture and Education.md
        - English/Interpretation/homework/Science.md
      - Learning Resources:
        - English/Interpretation/homework/Material.md    
    - Toefl:
      - English/toefl/index.md
      - Reading:
        - TPO65: English/toefl/reading/tpo65.md
        - TPO70: English/toefl/reading/tpo70.md
        - TPO71: English/toefl/reading/tpo71.md
        - TPO74: English/toefl/reading/tpo74.md
        - çœŸé¢˜1: English/toefl/reading/Real-1.md
        - çœŸé¢˜2: English/toefl/reading/Real-2.md
        - è§£ææ ¼å¼åŒ–å·¥å…·: English/toefl/reading/tpo_formatter.md
      - Listening:
        - TPO: English/toefl/listening/tpo.md
      - Speaking:
        - note: English/toefl/speaking/note.md 
        - ç‹¬ç«‹å£è¯­: English/toefl/speaking/task1.md 
      - Writing:
        - Exercise:
          - å­¦æœ¯å†™ä½œ: English/toefl/writing/exercise/Academic.md
          - ç»¼åˆå†™ä½œ: English/toefl/writing/exercise/Integrated.md
        - Note:
          - å­¦æœ¯å†™ä½œ: English/toefl/writing/note/Academic.md
          - ç»¼åˆå†™ä½œ: English/toefl/writing/note/Integrated.md
          - ä½œæ–‡ç´ æ: English/toefl/writing/note/material.md
    # - Material:
    #   - English/material/index.md
    #   - Words:
    #     - TPO: English/material/words/tpo.md
    #   - Writing:
    #     - åŠ³åŠ¨: English/material/writing/labor.md
    #     - å¿ƒç†å¥åº·: English/material/writing/mental.md
  - Research:
    - Research/index.md
    - Clip: Research/Clip.md
    - ç”µè·¯è¯†åˆ«: Research/Detection.md
    - Yolov11: Research/yolo.md
  - Others: 
    - Others/index.md
    - é›•ç‰ˆå°åˆ·ä¸è¯¾æœ¬æ–‡åŒ–: Others/PrintingCulture.md
    - æ§åˆ¶è®º: Others/control-theory.md
    - å¤§ç‰©å®éªŒ: Others/PhyExperiment.md
    - æ— çº¿ç½‘ç»œåº”ç”¨:
      - Others/Network/index.md
      - Lecture 4: Others/Network/Lecture4.md
      - Lecture 6: Others/Network/Lecture6.md
    - æœºå™¨äººæŠ€æœ¯ä¸å®è·µ:
      - Others/robot/index.md
      - Lec 1: Others/robot/1.md
      - Lec 2 æ—‹è½¬å‡ ä½• (Rotation Geometry): Others/robot/2.md
      - Lec 3 æ­£å‘è¿åŠ¨å­¦ (Forward kinematics): Others/robot/3.md
  - Writings:
    - Writings/index.md
    - Essay:
      - ä¸€ï¼šå½“å›æƒ³èµ·IAI: Writings/essay/01.md
      - äºŒï¼šå¸¦è®ºçš„ç¢ç¢å¿µ: Writings/essay/02.md
      - äº”ï¼šæ”¯æ•™æµæ°´è´¦: Writings/essay/05.md
      - å…«ï¼šAbout Slowist: Writings/essay/08.md
      - åï¼šACEEæŠ¥åä½“éªŒ: Writings/essay/10.md
      - åä¸€ï¼šAbout IAI: Writings/essay/11.md
      - åäºŒï¼šå¤§ä¸€å›å¿†å½•: Writings/essay/12.md
      - åä¸‰ï¼šåˆ†æµå»ºè®®: Writings/essay/13.md
      - åå››ï¼šè½¬ä¸“ä¸šè·¯ä¸Šçš„ç¢ç¢å¿µ: Writings/essay/14.md
      - åäº”ï¼šTuring Complete å…¨è¿‡ç¨‹æ—¥è®°: Writings/essay/15.md
      - åå…­ï¼šå¤§äºŒè¯¾ç¨‹æ€»ç»“: Writings/essay/16.md
      - äºŒåï¼šä¸€å°å›ä¿¡: Writings/essay/20.md
      - äºŒåä¸‰ï¼šWaiting For Sunrise: Writings/essay/23.md
    - Emotion:
      - ä¸‰: Writings/emotion/03.md
      - å››: Writings/emotion/04.md
      - å…­: Writings/emotion/06.md
      - ä¸ƒ: Writings/emotion/07.md  
      - ä¹: Writings/emotion/09.md
    - Record:
      - Writings/record/index.md
      - äºŒæœˆ: Writings/record/2025-02.md
