site_name: Lexie's Note
site_url: https://slowist-lee.github.io/notebook/
theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/book
  favicon: images/favicon.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to system preference
  font: false
    # code: JetBrains Mono
  # icon:
    # logo: assets/logo.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    # - navigation.sections
    - navigation.indexes
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
repo_url: https://github.com/lexie-423/notebook-by-zizi
repo_name: Lexie's Notebook
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lexie-423
    - icon: fontawesome/regular/envelope
      link: mushroomzizi@outlook.com

  feedback:
    title: æ­¤é¡µé¢æœ‰å¸®åŠ©å—ï¼Ÿ
    ratings:
      - icon: material/thumb-up-outline
        name: This page was helpful
        data: 1
        note: >-
          è°¢è°¢ä½ çš„åé¦ˆï¼
      - icon: material/thumb-down-outline
        name: This page could be improved
        data: 0
        note: >-
          Thanks for your feedback! 

plugins:
  - mermaid2: {}
  - search
  - callouts
  - encryptcontent:
      title_prefix: 'ğŸ”’'
      summary: 'è¯·è¾“å…¥å¯†ç æŸ¥çœ‹.'
      encryption_info_message: 'æ­¤å†…å®¹å·²åŠ å¯†, è¯·è¾“å…¥å¯†ç æŸ¥çœ‹.'
      decryption_failure_message: 'å¯†ç é”™è¯¯, å¦‚æœ‰éœ€è¦ï¼Œè¯·è”ç³»Lexie.'
      hljs: False
      encrypted_something:
        mkdocs-encrypted-toc: [nav, class]
  - statistics
  - changelog
  - git-revision-date-localized:
      enable_creation_date: true 
  - toc
markdown_extensions:
  - attr_list
  - md_in_html
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list



  # - mdx_truly_sane_lists
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight: # ä»£ç å—é«˜äº®
      auto_title: false # æ˜¾ç¤ºç¼–ç¨‹è¯­è¨€åç§°
extra_javascript:
  - js/katex.js
  - js/extra.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

copyright: Copyright &copy; 2025 Lexie Yu/All Rights Reserved. # å·¦ä¸‹è§’çš„ç‰ˆæƒå£°æ˜

nav:
  - Home:
    - index.md
    - æ›´æ–°è®°å½•: changelog.md
    - ç¬”è®°ç›®å½•: Content.md
    - To Do List: Writings/essay/22.md
  - SP:
    - SP/index.md
    - æ·±åº¦å­¦ä¹ : 
      - AI/DL/index.md
      - 1. Pytorch åŸºç¡€ä½¿ç”¨: AI/DL/1.md
      - 2.è‡ªåŠ¨å¾®åˆ†çš„Pytorchå®ç°: AI/DL/2.md
    - æœºå™¨å­¦ä¹ :
      - AI/ML/index.md
      - 0. æœºå™¨å­¦ä¹ æ¦‚è¿°: AI/ML/0.md
      - 1. ç»Ÿè®¡å­¦ä¹ &ç›‘ç£å­¦ä¹ æ¦‚è®º: AI/ML/1.md
      - 2. æ„ŸçŸ¥æœº: AI/ML/2.md
      - 3. SVMç®—æ³•: AI/ML/3.md
    - å…¶ä»–çŸ¥è¯†:
      - AI/Others/index.md
      - 1. æœç´¢: AI/Others/Search.md
  - Math: 
    - Math/index.md
    - é«˜ç­‰æ•°å­¦ï¼ˆå¾®ç§¯åˆ†ï¼‰:
      - æé™è®¡ç®—: Math/Math1/limit.md
    - å¤å˜å‡½æ•°ä¸ç§¯åˆ†å˜æ¢: Math/complex/index.md
    - æ¦‚ç‡è®ºä¸æ•°ç†ç»Ÿè®¡: Math/Probability/Error.md
    - æ•°å­¦å»ºæ¨¡: 
      - Math/MathModel/index.md
      - 1. æ•°å­¦è§„åˆ’: Math/MathModel/program/program.md
      - 2. å›¾è®ºæ¨¡å‹: Math/MathModel/graph/graph.md
      - 3. ç»„åˆä¼˜åŒ–: Math/MathModel/combination-optimize/note.md
      - 4. ä¹ é¢˜ç¬”è®°: Math/MathModel/exercise/index.md
      - 5. Review: Math/MathModel/review/note.md
      - 6. Test:
        - 24-25ç§‹å†¬æœŸæœ«(ACEE): Math/MathModel/test/index.md
  - Gallery:
    - å†™åœ¨å¼€å¤´: photo/index.md
    - Film è²æ—å·:
      - å: photo/Kodakfilm3/kodak3.md
  - Writings:
    - å†™åœ¨å¼€å¤´: Writing/index.md
    - å¤å…¸ä¹è¯„: 
      - Writing/Classical/intro.md
      - è°¢å°”ç›–Â·æ‹‰èµ«ç›å°¼è¯ºå¤«: Writing/Classical/Rach/about-rach.md
      - å¸•æ ¼å°¼å°¼ä¸»é¢˜ç‹‚æƒ³æ›² : Writing/Classical/Rach/Pag.md
